import numpy as np
import re
import hashlib
from models.embedding_model import get_embedding_model

# Tokens that are so generic they add no discriminative signal.
# They are stripped from VLM/query output, but NOT from catalog searchableText
# (which was generated by the backend enrichment pipeline and may include them
#  alongside genuinely useful words).
_GENERIC_TOKENS = {
    "generic", "product", "standard", "n/a", "general goods", "general",
    "full_frame", "unknown", "retail product", "retail", "pack",
}


def _is_generic_token(token: str) -> bool:
    return token.strip().lower() in _GENERIC_TOKENS


def build_catalog_text(product: dict) -> str:
    """
    Builds the canonical text representation for a CATALOG product to be indexed.
    Uses clean structured attributes (name, brand, category, variant, flavor, weight, description)
    to create a discriminative embedding vector without dilution from fine-print packaging noise.
    """
    if not isinstance(product, dict):
        return str(product)

    brand = product.get("brand") or product.get("brandName") or ""
    name = product.get("product_name") or product.get("name") or product.get("title") or ""
    flavor = product.get("flavor") or product.get("variant") or ""
    weight = product.get("weight") or product.get("netVolume") or ""
    desc = product.get("description") or ""

    cat_val = product.get("category")
    if isinstance(cat_val, dict):
        category = cat_val.get("name") or ""
    else:
        category = str(cat_val) if cat_val and not re.match(r'^[0-9a-fA-F]{24}$', str(cat_val)) else ""

    parts = [name, brand, category, flavor, weight, desc]
    clean_parts = [str(p).strip() for p in parts if str(p).strip() and str(p).strip() not in ["Generic Product", "N/A"]]
    combined = " ".join(clean_parts).strip()

    if combined:
        print(f"[EMBED] Catalog text (structured fields): '{combined}'")
        return combined

    # Fallback to searchableText if structured fields are missing
    st = (product.get("searchableText") or "").strip()
    if st:
        print(f"[EMBED] Catalog text (searchableText): '{st[:120]}'")
        return st

    return "retail product"


def build_query_text(vlm_data: dict, ocr_text: str = "") -> str:
    """
    Builds the query text for a SCANNED product at recognition time.

    Strategy:
      - Collect all VLM fields (brand, product_name, flavor, weight, category).
      - Keep fields that are not purely generic placeholder strings.
      - Always append raw OCR text (critical: OCR often contains real product words
        even when VLM outputs are generic).
      - If VLM provides NO discriminative data, use OCR alone.

    This is intentionally lenient: keeping more words increases the chance of
    overlapping with catalog vocabulary, especially for fallback hash embeddings.
    """
    if not isinstance(vlm_data, dict):
        vlm_data = {}

    brand = (vlm_data.get("brand") or vlm_data.get("brandName") or "").strip()
    name = (vlm_data.get("product_name") or vlm_data.get("name") or vlm_data.get("title") or "").strip()
    flavor = (vlm_data.get("flavor") or vlm_data.get("variant") or "").strip()
    weight = (vlm_data.get("weight") or vlm_data.get("netVolume") or "").strip()
    cat_val = vlm_data.get("category")
    if isinstance(cat_val, dict):
        category = cat_val.get("name") or ""
    else:
        category = str(cat_val).strip() if cat_val and not re.match(r'^[0-9a-fA-F]{24}$', str(cat_val)) else ""

    # Filter only purely-generic single-token placeholders from VLM output
    vlm_parts = []
    for tok in [brand, name, flavor, weight, category]:
        if tok and not _is_generic_token(tok):
            vlm_parts.append(tok)

    # Always include OCR text — it is real product text even if noisy
    ocr_clean = (ocr_text or "").strip()

    combined_parts = vlm_parts + ([ocr_clean] if ocr_clean and ocr_clean not in vlm_parts else [])
    combined = " ".join(combined_parts).strip()

    # Ultimate fallback: if everything is empty/generic, use raw OCR
    if not combined and ocr_clean:
        combined = ocr_clean

    print(f"[EMBED] Query text: '{combined}'")
    return combined


# ── Kept for backwards-compatibility — used internally by match_service ────────
def build_product_text(data: dict) -> str:
    """
    Unified entry-point: selects catalog or query representation automatically.

    - If `data` has a `searchableText` key  → catalog product  → build_catalog_text
    - Otherwise                              → VLM/query dict   → build_query_text
    """
    if isinstance(data, dict) and data.get("searchableText"):
        return build_catalog_text(data)
    # Treat as a VLM/query dict (no OCR text available separately here)
    return build_query_text(data, ocr_text=data.get("ocr_text") or "")


def generate_embedding(text: str) -> np.ndarray:
    """
    Generates a normalized 384-dimensional dense vector embedding for a given text.
    """
    clean_text = text.strip() if text else "retail product"
    model = get_embedding_model()

    if model is not None:
        try:
            vec = model.encode(clean_text, normalize_embeddings=True)
            arr = np.array(vec, dtype=np.float32)
            print(f"[EMBED DEBUG] Model: SentenceTransformer (all-MiniLM-L6-v2)")
            print(f"[EMBED DEBUG] Query dimension: {len(arr)}")
            print(f"[EMBED DEBUG] Query text: '{clean_text[:80]}'")
            return arr
        except Exception as e:
            print(f"[Product Embedding Error] SentenceTransformer encoding exception: {e}")

    # Deterministic Subword/Character N-Gram Hash fallback
    arr = generate_fallback_embedding(clean_text)
    print(f"[EMBED DEBUG] Model: MD5 Subword/N-Gram Deterministic Fallback")
    print(f"[EMBED DEBUG] Query dimension: {len(arr)}")
    print(f"[EMBED DEBUG] Query text: '{clean_text[:80]}'")
    return arr


def generate_fallback_embedding(text: str, dim: int = 384) -> np.ndarray:
    """
    Normalized 384-dim subword + character n-gram hash vector.
    Captures character-level similarity to match fuzzy OCR text with catalog products.
    """
    vec = np.zeros(dim, dtype=np.float32)
    clean = text.lower().strip()
    words = re.findall(r'\w+', clean)

    # 1. Whole word tokens (weight = 1.0)
    for word in words:
        h_val = int(hashlib.md5(f"w:{word}".encode("utf-8")).hexdigest(), 16)
        vec[h_val % dim] += 1.0

    # 2. Character 3-grams & 4-grams (weight = 0.5) — OCR typo tolerance
    padded = f" {clean} "
    for n in (3, 4):
        for i in range(len(padded) - n + 1):
            ngram = padded[i:i + n]
            h_val = int(hashlib.md5(f"c:{ngram}".encode("utf-8")).hexdigest(), 16)
            vec[h_val % dim] += 0.5

    norm = np.linalg.norm(vec)
    if norm > 0:
        vec /= norm
    return vec
