module.exports = [
  "Bakery",
  "Beverages",
  "Biscuits",
  "Breakfast & Cereals",
  "Chocolates & Candy",
  "Dairy",
  "Dry Fruits & Nuts",
  "Frozen Foods",
  "Fruits & Vegetables",
  "Grocery & Staples",
  "Health & Wellness",
  "Household",
  "Ice Cream",
  "Instant Foods",
  "Kitchen Essentials",
  "Personal Care",
  "Pet Care",
  "Pickles & Sauces",
  "Ready to Eat",
  "Rice, Flour & Pulses",
  "Snacks",
  "Spices & Masalas",
  "Tea & Coffee",
  "Water & Soft Drinks"
];
